apiVersion: apps/v1
kind: Deployment
metadata:
  name: salarypredictionv2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mldeployment
  template:
    metadata:
      labels:
        app: mldeployment
    spec:
      containers:
      - name: ml-app
        image: gcr.io/glowing-space-343410/myapp:v1
        ports:
        - containerPort: 8080